### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGTSTP'

### ISSUE THREAD

**Issue by aharris02** [gadelat/Bulk-Bing-Image-downloader#3]
Getting `bbid.py", line 107, in <module>
    signal.signal(signal.SIGTSTP, backup_history)
AttributeError: module 'signal' has no attribute 'SIGTSTP'` when I run the script, and search didn't turn up much for the error other than signal has been deprecated for a while. Any suggestions?

**Comment by gadelat** [comment]
I think you are running it via python2. This is python3 project. Please run it as referred in readme.

**Comment by aharris02** [comment]
Thanks for the reply. I do have both installed. Was running with the Python3 executable, but having both could definitely be the issue.

**Comment by gadelat** [comment]
Please show me how do you run the script and specify what's you operating system/distribution

**Comment by internetbird** [comment]
I am having the same problem. Running Python 3.5.1 on Windows 7 OS

I run the script using the following command: python bbid.py -s "some search"
