### ISSUE TITLE
Different performance on different computers

### ISSUE THREAD

**Issue by sym44** [gadelat/Bulk-Bing-Image-downloader#5]
Hi, I've met a problem that on my mac, bbid can download over 500 images at a time. While on remote ubuntu node, it can only download less than 100 images, with same query and parameters. Could someone explain this a bit?

Thanks in advance!

**Comment by gadelat** [comment]
Performance is dependent on CPU parallel processing power and bandwidth. These tend to be lower on VPS.

**Comment by sym44** [comment]
@gadelat  Sorry for the misleading title. The issue here is the total amount of images downloaded. (So that is only around 20 or so images could be downloaded on VPS for query like 'earth') Later, I found it may have something to do with the 'break' statement in line 80. For some reason, on VPS, this break will break the entire while True loop. While on my mac, the program will keep running for many iterations.

**Comment by gadelat** [comment]
That break is supposed to break whole loop. It looks like bing returns different results on both machines. Print out response from line 76 on both machines and do a comparison.

**Comment by gadelat** [comment]
Closing, as this doesn't look like a valid issue
