### ISSUE TITLE
rename downloaded file by search string

### ISSUE THREAD

**Issue by PuttySandwich** [gadelat/Bulk-Bing-Image-downloader#53]
It would be very nice to have an option to rename each downloaded file to the search string. So if the search term is pizza, any resulting images would be renamed to pizz.jpg, pizza1.jpg, etc. 

That way if you're using a list it's a lot easier to find the downloaded image for each query.

**Comment by ostrolucky** [comment]
If you use wordlist, BBID automatically uses separate folders for each term. For single keyword, you can specify folder via -o argument. I believe this is good enough.
