### ISSUE TITLE
-f, path to a string, how does it work ?

### ISSUE THREAD

**Issue by Maxruuu** [gadelat/Bulk-Bing-Image-downloader#54]
Hey, i have a list of words in a text file. I use -f argurment but it takes only the first word. Am i using it wrong ?

**Comment by ostrolucky** [comment]
Are you specifying a limit? You are probably running into https://github.com/ostrolucky/Bulk-Bing-Image-downloader/issues/52

**Comment by Maxruuu** [comment]
yep, --limit 5
