### ISSUE TITLE
Ceases to work when duplicate image is found

### ISSUE THREAD

**Issue by DedrichVonDorn** [gadelat/Bulk-Bing-Image-downloader#6]
Script fails when trying to write a duplicate filename. Here is the error

FAIL Image is a duplicate of 400.jpg, not saving 2100.jpg
history_dumped
history_dumped
Traceback (most recent call last):
  File "./bbid.py", line 152, in <module>
    if fetch_images_from_keyword(keyword,output_dir):
  File "./bbid.py", line 85, in fetch_images_from_keyword
    t.start()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 844, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by gadelat** [comment]
I think it's just coincidence that it fails at that point, as it works fine for me. The most important information is this:

>  RuntimeError: can't start new thread

Number of threads specified in the script is probably too much for your system. Try to lower the number of threads on line 7

**Comment by sanghoon** [comment]
This issue will be resolved after merging PR#7

**Comment by gadelat** [comment]
I believe this might have been fixed in most recent commit. Let us know if not.
